apiVersion: v1
appVersion: "1.0"
description: A helm chart for deploying raw manifests
name: raw
version: 1.0.0
source:
  - https://github.com/paulczar/charts
home: https://tech.paulcz.net/charts
maintainers:
  - email: username.taken@gmail.com
    name: paulczar
